// Constants for rewards
export const XP_REWARDS = {
  COMPLETE_FLASHCARD: 10,
  COMPLETE_QUIZ: 50,
  CORRECT_QUIZ_ANSWER: 15,
  DEFEAT_ALIEN: 75,
  COMPLETE_MODULE: 200,
  COMPLETE_GALAXY: 500,
  DAILY_STREAK: 25,
  STREAK_MILESTONE: 100 // For every 7 days
}; 